export default {
    card: {
      name: "Sun Position Card",
      description: "Posición del Sol y la Luna con imágenes personalizadas.",
    },
    error: {
      no_sun_entity: "Por favor, define una entidad de sol.",
      entity_not_found: "Entidad no encontrada: ",
    },
      sun_state: {
      below_horizon: "Bajo el horizonte",
      dawn: "Alba",
      dusk: "Crepúsculo",
      morning: "Mañana",
      noon: "Mediodía",
      afternoon: "Tarde",
      evening: "Anochecer",
    },
    moon_phase: {
      new_moon: "Luna nueva",
      waxing_crescent: "Luna creciente",
      first_quarter: "Cuarto creciente",
      waxing_gibbous: "Gibosa creciente",
      full_moon: "Luna llena",
      waning_gibbous: "Gibosa menguante",
      last_quarter: "Cuarto menguante",
      waning_crescent: "Luna menguante",
    },
    weather_state: {
      "clear-night": "Despejado (noche)",
      cloudy: "Nublado",
      fog: "Niebla",
      hail: "Granizo",
      lightning: "Relámpagos",
      "lightning-rainy": "Tormenta eléctrica",
      partlycloudy: "Parcialmente nublado",
      pouring: "Lluvia intensa",
      rainy: "Lluvia",
      snowy: "Nieve",
      "snowy-rainy": "Nieve y lluvia",
      sunny: "Soleado",
      windy: "Ventoso",
      "windy-variant": "Ventoso",
      exceptional: "Excepcional",
    },
    time_entry: {
      current: "Actual",
      azimuth: "Azimut",
      elevation: "Elevación",
      daylight_duration: "Duración de luz diurna",
      day_comparison: "Comparativa del día",
      next_rising: "Amanecer",
      next_setting: "Atardecer",
      next_dawn: "Alba",
      next_dusk: "Crepúsculo",
      next_noon: "Mediodía",
      next_midnight: "Medianoche",
      moon_phase: "Fase lunar",
      weather: "Tiempo",
    },
    editor: {
      entity: "Entidad de Sol",
      moon_entity: "Entidad de Luna (Opcional)",
      weather_entity: "Entidad de Tiempo (Opcional)",
      temp_entity: "Entidad de Temperatura (Opcional, anula el tiempo)",
      main_options: "Opciones de visualización",
      view_mode: "Modo de vista",
      view_mode_classic: "Clásico (6 Imágenes)",
      view_mode_calculated: "Calculado (Solo elevación)",
      view_mode_arc: "Arco (Movimiento 180°)",
      show_image: "Mostrar posición del sol (Imagen)",
      show_weather_badge: "Mostrar insignia del tiempo",
      animate_images: "Animar imágenes (excepto mañana/crepúsculo)",
      sun_size: "Tamaño Sol/Luna (Solo en Arco)",
      state_position: "Posición del estado",
      state_pos_above: "Sobre la imagen",
      state_pos_in_list: "En la lista",
      state_pos_hide: "Ocultar",
      moon_phase_position: "Posición de la fase lunar",
      hide_moon_phase_on_day: "Ocultar fase lunar durante el día",
      show_night_arc: "Mostrar arco lunar (180°)",
      show_moon_icon_in_text: "Mostrar icono de la luna en el texto",
      show_dividers: "Mostrar divisores",
      show_degrees: "Mostrar grados (Azimut/Elevación)",
      show_degrees_in_list: "Mostrar grados en la lista",
      time_position: "Posición de la hora",
      time_pos_below: "Bajo la imagen",
      time_pos_above: "Sobre la imagen",
      time_pos_right: "A la derecha de la imagen",
      time_list_format: "Alineación de la lista de horas",
      time_format_centered: "Centrado",
      time_format_block: "Bloque",
      times_to_show: "Seleccionar horas",
      use_12h_format: "Usar formato 12h (AM/PM)",
      language: "Idioma",
      language_auto: "Automático (Home Assistant)",
      solar_entity: "Entidad de energía solar (Opcional)",
      show_solar_badge: "Mostrar insignia de energía solar",
      advanced_options: "Umbrales (Avanzado)",
      morning_azimuth: "Azimut de la mañana",
      noon_azimuth: "Azimut del mediodía",
      afternoon_azimuth: "Azimut de la tarde",
      dusk_elevation: "Elevación del crepúsculo",
    },
  };
